server:
  port: 8080

spring:
  application:
    name: phoenix-fitness-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/phoenix?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: "@123"  # Quote the password to handle the @ character
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  security:
    user:
      name: admin
      password: admin123

jwt:
  secret: phoenixFitnessStudioSecretKeyForJWTTokenGeneration2025
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.phoenixfitness: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

cors:
  allowed-origins: http://localhost:5173,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  allow-credentials: true
